# Site settings
title:    HustLion
tagline:          'a developer who is a Sci-fi enthusiast'
email: hustlionM@qq.com
description: > # this means to ignore newlines until "baseurl:"
  This is HustLion's programming blog. Multiple natural languages may appear in any posts including Chinese, English, Spanish, French, Deutsch, Japanese, Korean, Russian, Italian. HustLion posts his demo projects and tutorials here.
baseurl: ""
url: "http://hustlion.github.io" # the base hostname & protocol for your site

paginate:         10
github_username:  HustLion

# Build settings
markdown: kramdown

# Markdown Processors
kramdown:
	math_engine:	mathjax

# Permalinks
permalink:        pretty
relative_permalinks: true

gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
