# Site settings
title: HustLion's programming blog
email: hustlionM@qq.com
description: > # this means to ignore newlines until "baseurl:"
  This is HustLion's programming blog. HustLion posts his demo projects and tutorials here.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

github_username:  HustLion

# Build settings
markdown: kramdown

gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
